package com.agrilink.model.enums;

public enum OrderStatus {
    PENDING_PAYMENT,
    PAYMENT_SUBMITTED,
    PAYMENT_VERIFIED,
    FARMER_ACCEPTED,
    FARMER_REJECTED,
    READY_FOR_PICKUP,
    TRANSPORT_REQUESTED,
    TRANSPORT_ASSIGNED,
    GOING_TO_PICKUP,
    ARRIVED_AT_PICKUP,
    PICKED_UP,
    IN_TRANSIT,
    NEAR_DESTINATION,
    DELIVERED,
    COMPLETED,
    CANCELLED
}
